import type { Metadata } from "next";
import "./globals.css";
import { RegisterMcpServer } from "@/components/mcp/mcp-server";
import { z } from "zod";
import { ResourceTemplate } from "@modelcontextprotocol/sdk/server/mcp.js";
import { MyMcp } from "./my-mcp";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MyMcp>{children}</MyMcp>
      </body>
    </html>
  );
}
